export interface IconEntry {
  slug: string
  label: string
  category: string
  source: 'simple' | 'lucide'
}

export const ICON_CATEGORIES = [
  { key: 'all', label: '全部' },
  { key: 'brands', label: '品牌' },
  { key: 'media', label: '媒体' },
  { key: 'social', label: '社交' },
  { key: 'tool', label: '工具' },
  { key: 'cloud', label: '云服务' },
  { key: 'hardware', label: '硬件' },
  { key: 'file', label: '文件' },
  { key: 'finance', label: '金融' },
  { key: 'arrow', label: '箭头' },
  { key: 'other', label: '其他' },
]

export const ICON_CATALOG: IconEntry[] = [
  // ── Brands ─────────────────────────────────────────
  { slug: 'github', label: 'GitHub', category: 'brands', source: 'simple' },
  { slug: 'gitlab', label: 'GitLab', category: 'brands', source: 'simple' },
  { slug: 'bitbucket', label: 'Bitbucket', category: 'brands', source: 'simple' },
  { slug: 'stackoverflow', label: 'StackOverflow', category: 'brands', source: 'simple' },
  { slug: 'git', label: 'Git', category: 'brands', source: 'simple' },
  { slug: 'npm', label: 'NPM', category: 'brands', source: 'simple' },
  { slug: 'yarn', label: 'Yarn', category: 'brands', source: 'simple' },
  { slug: 'docker', label: 'Docker', category: 'brands', source: 'simple' },
  { slug: 'kubernetes', label: 'Kubernetes', category: 'brands', source: 'simple' },
  { slug: 'jira', label: 'Jira', category: 'brands', source: 'simple' },
  { slug: 'figma', label: 'Figma', category: 'brands', source: 'simple' },
  { slug: 'markdown', label: 'Markdown', category: 'brands', source: 'simple' },
  { slug: 'python', label: 'Python', category: 'brands', source: 'simple' },
  { slug: 'javascript', label: 'JavaScript', category: 'brands', source: 'simple' },
  { slug: 'vuedotjs', label: 'Vue.js', category: 'brands', source: 'simple' },
  { slug: 'react', label: 'React', category: 'brands', source: 'simple' },
  { slug: 'angular', label: 'Angular', category: 'brands', source: 'simple' },
  { slug: 'nodedotjs', label: 'Node.js', category: 'brands', source: 'simple' },
  { slug: 'svelte', label: 'Svelte', category: 'brands', source: 'simple' },
  { slug: 'html5', label: 'HTML5', category: 'brands', source: 'simple' },
  { slug: 'css3', label: 'CSS3', category: 'brands', source: 'simple' },
  { slug: 'bootstrap', label: 'Bootstrap', category: 'brands', source: 'simple' },
  { slug: 'sass', label: 'Sass', category: 'brands', source: 'simple' },
  { slug: 'php', label: 'PHP', category: 'brands', source: 'simple' },
  { slug: 'java', label: 'Java', category: 'brands', source: 'simple' },
  { slug: 'swift', label: 'Swift', category: 'brands', source: 'simple' },
  { slug: 'rust', label: 'Rust', category: 'brands', source: 'simple' },
  { slug: 'go', label: 'Go', category: 'brands', source: 'simple' },
  { slug: 'kotlin', label: 'Kotlin', category: 'brands', source: 'simple' },
  { slug: 'flutter', label: 'Flutter', category: 'brands', source: 'simple' },
  { slug: 'typescript', label: 'TypeScript', category: 'brands', source: 'simple' },
  { slug: 'ubuntu', label: 'Ubuntu', category: 'brands', source: 'simple' },
  { slug: 'centos', label: 'CentOS', category: 'brands', source: 'simple' },
  { slug: 'fedora', label: 'Fedora', category: 'brands', source: 'simple' },
  { slug: 'redhat', label: 'Red Hat', category: 'brands', source: 'simple' },
  { slug: 'linux', label: 'Linux', category: 'brands', source: 'simple' },
  { slug: 'apple', label: 'Apple', category: 'brands', source: 'simple' },
  { slug: 'windows', label: 'Windows', category: 'brands', source: 'simple' },
  { slug: 'android', label: 'Android', category: 'brands', source: 'simple' },
  { slug: 'raspberrypi', label: '树莓派', category: 'brands', source: 'simple' },
  { slug: 'googlechrome', label: 'Chrome', category: 'brands', source: 'simple' },
  { slug: 'firefox', label: 'Firefox', category: 'brands', source: 'simple' },
  { slug: 'microsoftedge', label: 'Edge', category: 'brands', source: 'simple' },
  { slug: 'safari', label: 'Safari', category: 'brands', source: 'simple' },
  { slug: 'opera', label: 'Opera', category: 'brands', source: 'simple' },
  { slug: 'aws', label: 'AWS', category: 'brands', source: 'simple' },
  { slug: 'cloudflare', label: 'Cloudflare', category: 'brands', source: 'simple' },
  { slug: 'digitalocean', label: 'DigitalOcean', category: 'brands', source: 'simple' },
  { slug: 'googlecloud', label: 'Google Cloud', category: 'brands', source: 'simple' },
  { slug: 'microsoft', label: 'Microsoft', category: 'brands', source: 'simple' },
  { slug: 'azure', label: 'Azure', category: 'brands', source: 'simple' },
  { slug: 'heroku', label: 'Heroku', category: 'brands', source: 'simple' },
  { slug: 'netlify', label: 'Netlify', category: 'brands', source: 'simple' },
  { slug: 'vercel', label: 'Vercel', category: 'brands', source: 'simple' },
  { slug: 'wordpress', label: 'WordPress', category: 'brands', source: 'simple' },
  { slug: 'drupal', label: 'Drupal', category: 'brands', source: 'simple' },
  { slug: 'joomla', label: 'Joomla', category: 'brands', source: 'simple' },
  { slug: 'amazon', label: 'Amazon', category: 'brands', source: 'simple' },
  { slug: 'ebay', label: 'eBay', category: 'brands', source: 'simple' },
  { slug: 'shopify', label: 'Shopify', category: 'brands', source: 'simple' },
  { slug: 'etsy', label: 'Etsy', category: 'brands', source: 'simple' },
  { slug: 'magento', label: 'Magento', category: 'brands', source: 'simple' },
  { slug: 'paypal', label: 'PayPal', category: 'brands', source: 'simple' },
  { slug: 'stripe', label: 'Stripe', category: 'brands', source: 'simple' },
  { slug: 'alipay', label: '支付宝', category: 'brands', source: 'simple' },
  { slug: 'cc-visa', label: 'Visa', category: 'brands', source: 'simple' },
  { slug: 'cc-mastercard', label: 'Mastercard', category: 'brands', source: 'simple' },
  { slug: 'american-express', label: 'American Express', category: 'brands', source: 'simple' },
  { slug: 'adobe', label: 'Adobe', category: 'brands', source: 'simple' },
  { slug: 'uber', label: 'Uber', category: 'brands', source: 'simple' },
  { slug: 'airbnb', label: 'Airbnb', category: 'brands', source: 'simple' },
  { slug: 'tripadvisor', label: 'TripAdvisor', category: 'brands', source: 'simple' },
  { slug: 'adguard', label: 'AdGuard', category: 'brands', source: 'simple' },

  // ── Media ──────────────────────────────────────────
  { slug: 'youtube', label: 'YouTube', category: 'media', source: 'simple' },
  { slug: 'bilibili', label: '哔哩哔哩', category: 'media', source: 'simple' },
  { slug: 'twitch', label: 'Twitch', category: 'media', source: 'simple' },
  { slug: 'vimeo', label: 'Vimeo', category: 'media', source: 'simple' },
  { slug: 'spotify', label: 'Spotify', category: 'media', source: 'simple' },
  { slug: 'soundcloud', label: 'SoundCloud', category: 'media', source: 'simple' },
  { slug: 'lastfm', label: 'Last.fm', category: 'media', source: 'simple' },
  { slug: 'deezer', label: 'Deezer', category: 'media', source: 'simple' },
  { slug: 'imdb', label: 'IMDb', category: 'media', source: 'simple' },
  { slug: 'tiktok', label: 'TikTok', category: 'media', source: 'simple' },
  { slug: 'snapchat', label: 'Snapchat', category: 'media', source: 'simple' },
  { slug: 'pinterest', label: 'Pinterest', category: 'media', source: 'simple' },
  { slug: 'film', label: '影视', category: 'media', source: 'lucide' },
  { slug: 'video', label: '视频', category: 'media', source: 'lucide' },
  { slug: 'music', label: '音乐', category: 'media', source: 'lucide' },
  { slug: 'headphones', label: '耳机', category: 'media', source: 'lucide' },
  { slug: 'mic', label: '麦克风', category: 'media', source: 'lucide' },
  { slug: 'camera', label: '相机', category: 'media', source: 'lucide' },
  { slug: 'image', label: '图片', category: 'media', source: 'lucide' },
  { slug: 'palette', label: '调色板', category: 'media', source: 'lucide' },
  { slug: 'tv', label: '电视', category: 'media', source: 'lucide' },

  // ── Social ─────────────────────────────────────────
  { slug: 'wechat', label: '微信', category: 'social', source: 'simple' },
  { slug: 'sinaweibo', label: '微博', category: 'social', source: 'simple' },
  { slug: 'zhihu', label: '知乎', category: 'social', source: 'simple' },
  { slug: 'tencentqq', label: 'QQ', category: 'social', source: 'simple' },
  { slug: 'twitter', label: 'Twitter', category: 'social', source: 'simple' },
  { slug: 'facebook', label: 'Facebook', category: 'social', source: 'simple' },
  { slug: 'instagram', label: 'Instagram', category: 'social', source: 'simple' },
  { slug: 'telegram', label: 'Telegram', category: 'social', source: 'simple' },
  { slug: 'discord', label: 'Discord', category: 'social', source: 'simple' },
  { slug: 'slack', label: 'Slack', category: 'social', source: 'simple' },
  { slug: 'reddit', label: 'Reddit', category: 'social', source: 'simple' },
  { slug: 'linkedin', label: 'LinkedIn', category: 'social', source: 'simple' },
  { slug: 'whatsapp', label: 'WhatsApp', category: 'social', source: 'simple' },
  { slug: 'skype', label: 'Skype', category: 'social', source: 'simple' },
  { slug: 'signal', label: 'Signal', category: 'social', source: 'simple' },
  { slug: 'line', label: 'LINE', category: 'social', source: 'simple' },
  { slug: 'medium', label: 'Medium', category: 'social', source: 'simple' },
  { slug: 'mastodon', label: 'Mastodon', category: 'social', source: 'simple' },
  { slug: 'goodreads', label: 'Goodreads', category: 'social', source: 'simple' },
  { slug: 'mail', label: '邮件', category: 'social', source: 'lucide' },
  { slug: 'message-square', label: '聊天', category: 'social', source: 'lucide' },
  { slug: 'share-2', label: '分享', category: 'social', source: 'lucide' },
  { slug: 'rss', label: 'RSS', category: 'social', source: 'lucide' },
  { slug: 'users', label: '好友', category: 'social', source: 'lucide' },

  // ── Tool ───────────────────────────────────────────
  { slug: 'settings', label: '设置', category: 'tool', source: 'lucide' },
  { slug: 'wrench', label: '工具', category: 'tool', source: 'lucide' },
  { slug: 'search', label: '搜索', category: 'tool', source: 'lucide' },
  { slug: 'download', label: '下载', category: 'tool', source: 'lucide' },
  { slug: 'upload', label: '上传', category: 'tool', source: 'lucide' },
  { slug: 'refresh-cw', label: '同步', category: 'tool', source: 'lucide' },
  { slug: 'history', label: '历史', category: 'tool', source: 'lucide' },
  { slug: 'code', label: '代码', category: 'tool', source: 'lucide' },
  { slug: 'terminal', label: '终端', category: 'tool', source: 'lucide' },
  { slug: 'database', label: '数据库', category: 'tool', source: 'lucide' },
  { slug: 'bar-chart-3', label: '图表', category: 'tool', source: 'lucide' },
  { slug: 'trending-up', label: '趋势', category: 'tool', source: 'lucide' },
  { slug: 'gauge', label: '仪表盘', category: 'tool', source: 'lucide' },
  { slug: 'qrcode', label: '二维码', category: 'tool', source: 'lucide' },
  { slug: 'printer', label: '打印', category: 'tool', source: 'lucide' },
  { slug: 'calculator', label: '计算器', category: 'tool', source: 'lucide' },
  { slug: 'list-checks', label: '清单', category: 'tool', source: 'lucide' },
  { slug: 'calendar', label: '日历', category: 'tool', source: 'lucide' },
  { slug: 'clock', label: '时钟', category: 'tool', source: 'lucide' },
  { slug: 'bell', label: '通知', category: 'tool', source: 'lucide' },
  { slug: 'bookmark', label: '书签', category: 'tool', source: 'lucide' },
  { slug: 'paperclip', label: '附件', category: 'tool', source: 'lucide' },
  { slug: 'scissors', label: '剪切', category: 'tool', source: 'lucide' },
  { slug: 'compass', label: '指南针', category: 'tool', source: 'lucide' },
  { slug: 'map', label: '地图', category: 'tool', source: 'lucide' },
  { slug: 'map-pin', label: '图钉', category: 'tool', source: 'lucide' },
  { slug: 'stopwatch', label: '秒表', category: 'tool', source: 'lucide' },
  { slug: 'key', label: '密钥', category: 'tool', source: 'lucide' },
  { slug: 'shield', label: '盾牌', category: 'tool', source: 'lucide' },

  // ── Cloud ──────────────────────────────────────────
  { slug: 'cloud', label: '云', category: 'cloud', source: 'lucide' },
  { slug: 'server', label: '服务器', category: 'cloud', source: 'lucide' },
  { slug: 'hard-drive', label: '硬盘', category: 'cloud', source: 'lucide' },
  { slug: 'wifi', label: 'WiFi', category: 'cloud', source: 'lucide' },
  { slug: 'shield-off', label: '安全', category: 'cloud', source: 'lucide' },
  { slug: 'lock', label: '锁', category: 'cloud', source: 'lucide' },
  { slug: 'unlock', label: '解锁', category: 'cloud', source: 'lucide' },
  { slug: 'globe', label: '全球', category: 'cloud', source: 'lucide' },
  { slug: 'map-pin', label: '位置', category: 'cloud', source: 'lucide' },
  { slug: 'shopping-cart', label: '购物车', category: 'cloud', source: 'lucide' },
  { slug: 'store', label: '商店', category: 'cloud', source: 'lucide' },
  { slug: 'package', label: '包裹', category: 'cloud', source: 'lucide' },
  { slug: 'dropbox', label: 'Dropbox', category: 'cloud', source: 'simple' },
  { slug: 'googledrive', label: 'Google Drive', category: 'cloud', source: 'simple' },
  { slug: 'onedrive', label: 'OneDrive', category: 'cloud', source: 'simple' },

  // ── Hardware ───────────────────────────────────────
  { slug: 'monitor', label: '桌面', category: 'hardware', source: 'lucide' },
  { slug: 'laptop', label: '笔记本', category: 'hardware', source: 'lucide' },
  { slug: 'tablet', label: '平板', category: 'hardware', source: 'lucide' },
  { slug: 'smartphone', label: '手机', category: 'hardware', source: 'lucide' },
  { slug: 'cpu', label: '芯片', category: 'hardware', source: 'lucide' },
  { slug: 'gamepad-2', label: '游戏手柄', category: 'hardware', source: 'lucide' },
  { slug: 'keyboard', label: '键盘', category: 'hardware', source: 'lucide' },
  { slug: 'mouse', label: '鼠标', category: 'hardware', source: 'lucide' },
  { slug: 'headphones', label: '耳机', category: 'hardware', source: 'lucide' },
  { slug: 'battery-full', label: '满电', category: 'hardware', source: 'lucide' },
  { slug: 'battery-medium', label: '半电', category: 'hardware', source: 'lucide' },
  { slug: 'battery-low', label: '没电', category: 'hardware', source: 'lucide' },
  { slug: 'printer', label: '打印机', category: 'hardware', source: 'lucide' },
  { slug: 'steam', label: 'Steam', category: 'hardware', source: 'simple' },
  { slug: 'xbox', label: 'Xbox', category: 'hardware', source: 'simple' },
  { slug: 'playstation', label: 'PlayStation', category: 'hardware', source: 'simple' },

  // ── File ───────────────────────────────────────────
  { slug: 'file', label: '文件', category: 'file', source: 'lucide' },
  { slug: 'file-text', label: '文档', category: 'file', source: 'lucide' },
  { slug: 'file-image', label: '图片文件', category: 'file', source: 'lucide' },
  { slug: 'file-archive', label: '压缩包', category: 'file', source: 'lucide' },
  { slug: 'file-audio', label: '音频文件', category: 'file', source: 'lucide' },
  { slug: 'file-video', label: '视频文件', category: 'file', source: 'lucide' },
  { slug: 'file-code', label: '代码文件', category: 'file', source: 'lucide' },
  { slug: 'file-spreadsheet', label: '表格', category: 'file', source: 'lucide' },
  { slug: 'folder', label: '文件夹', category: 'file', source: 'lucide' },
  { slug: 'folder-open', label: '打开文件夹', category: 'file', source: 'lucide' },
  { slug: 'folder-plus', label: '新建文件夹', category: 'file', source: 'lucide' },
  { slug: 'copy', label: '复制', category: 'file', source: 'lucide' },
  { slug: 'clipboard-paste', label: '粘贴', category: 'file', source: 'lucide' },
  { slug: 'save', label: '保存', category: 'file', source: 'lucide' },
  { slug: 'archive', label: '归档', category: 'file', source: 'lucide' },

  // ── Finance ────────────────────────────────────────
  { slug: 'dollar-sign', label: '美元', category: 'finance', source: 'lucide' },
  { slug: 'euro', label: '欧元', category: 'finance', source: 'lucide' },
  { slug: 'coins', label: '金币', category: 'finance', source: 'lucide' },
  { slug: 'credit-card', label: '信用卡', category: 'finance', source: 'lucide' },
  { slug: 'wallet', label: '钱包', category: 'finance', source: 'lucide' },
  { slug: 'piggy-bank', label: '存钱罐', category: 'finance', source: 'lucide' },
  { slug: 'pie-chart', label: '饼图', category: 'finance', source: 'lucide' },
  { slug: 'banknote', label: '钞票', category: 'finance', source: 'lucide' },
  { slug: 'percent', label: '百分比', category: 'finance', source: 'lucide' },
  { slug: 'landmark', label: '银行', category: 'finance', source: 'lucide' },
  { slug: 'bitcoin', label: 'Bitcoin', category: 'finance', source: 'simple' },
  { slug: 'ethereum', label: 'Ethereum', category: 'finance', source: 'simple' },

  // ── Arrow ──────────────────────────────────────────
  { slug: 'arrow-right', label: '右箭头', category: 'arrow', source: 'lucide' },
  { slug: 'arrow-left', label: '左箭头', category: 'arrow', source: 'lucide' },
  { slug: 'arrow-up', label: '上箭头', category: 'arrow', source: 'lucide' },
  { slug: 'arrow-down', label: '下箭头', category: 'arrow', source: 'lucide' },
  { slug: 'arrow-up-right', label: '外链', category: 'arrow', source: 'lucide' },
  { slug: 'link', label: '链接', category: 'arrow', source: 'lucide' },
  { slug: 'log-in', label: '登录', category: 'arrow', source: 'lucide' },
  { slug: 'log-out', label: '登出', category: 'arrow', source: 'lucide' },
  { slug: 'undo', label: '撤销', category: 'arrow', source: 'lucide' },
  { slug: 'redo', label: '重做', category: 'arrow', source: 'lucide' },
  { slug: 'chevron-right', label: '右角', category: 'arrow', source: 'lucide' },
  { slug: 'chevron-left', label: '左角', category: 'arrow', source: 'lucide' },
  { slug: 'chevron-up', label: '上角', category: 'arrow', source: 'lucide' },
  { slug: 'chevron-down', label: '下角', category: 'arrow', source: 'lucide' },
  { slug: 'chevrons-right', label: '右双角', category: 'arrow', source: 'lucide' },
  { slug: 'chevrons-left', label: '左双角', category: 'arrow', source: 'lucide' },
  { slug: 'external-link', label: '新窗口', category: 'arrow', source: 'lucide' },

  // ── Other ──────────────────────────────────────────
  { slug: 'star', label: '星星', category: 'other', source: 'lucide' },
  { slug: 'heart', label: '心', category: 'other', source: 'lucide' },
  { slug: 'flag', label: '旗帜', category: 'other', source: 'lucide' },
  { slug: 'tag', label: '标签', category: 'other', source: 'lucide' },
  { slug: 'home', label: '首页', category: 'other', source: 'lucide' },
  { slug: 'user', label: '用户', category: 'other', source: 'lucide' },
  { slug: 'users', label: '用户组', category: 'other', source: 'lucide' },
  { slug: 'crown', label: '皇冠', category: 'other', source: 'lucide' },
  { slug: 'gem', label: '宝石', category: 'other', source: 'lucide' },
  { slug: 'flame', label: '火', category: 'other', source: 'lucide' },
  { slug: 'zap', label: '闪电', category: 'other', source: 'lucide' },
  { slug: 'lightbulb', label: '灯泡', category: 'other', source: 'lucide' },
  { slug: 'moon', label: '月亮', category: 'other', source: 'lucide' },
  { slug: 'sun', label: '太阳', category: 'other', source: 'lucide' },
  { slug: 'book', label: '书籍', category: 'other', source: 'lucide' },
  { slug: 'newspaper', label: '新闻', category: 'other', source: 'lucide' },
  { slug: 'graduation-cap', label: '毕业帽', category: 'other', source: 'lucide' },
  { slug: 'medal', label: '奖牌', category: 'other', source: 'lucide' },
  { slug: 'trophy', label: '奖杯', category: 'other', source: 'lucide' },
  { slug: 'pen-tool', label: '博客', category: 'other', source: 'lucide' },
  { slug: 'languages', label: '语言', category: 'other', source: 'lucide' },
  { slug: 'wand-2', label: '魔法', category: 'other', source: 'lucide' },
  { slug: 'shopping-cart', label: '加购', category: 'other', source: 'lucide' },
  { slug: 'eye', label: '眼睛', category: 'other', source: 'lucide' },
  { slug: 'rocket', label: '火箭', category: 'other', source: 'lucide' },
  { slug: 'plane', label: '飞机', category: 'other', source: 'lucide' },
  { slug: 'car', label: '汽车', category: 'other', source: 'lucide' },
  { slug: 'train', label: '火车', category: 'other', source: 'lucide' },
  { slug: 'building', label: '大楼', category: 'other', source: 'lucide' },
  { slug: 'umbrella', label: '雨伞', category: 'other', source: 'lucide' },
  { slug: 'paw-print', label: '爪子', category: 'other', source: 'lucide' },
  { slug: 'leaf', label: '叶子', category: 'other', source: 'lucide' },
  { slug: 'tree-pine', label: '树', category: 'other', source: 'lucide' },
  { slug: 'pizza', label: '披萨', category: 'other', source: 'lucide' },
  { slug: 'coffee', label: '咖啡', category: 'other', source: 'lucide' },
  { slug: 'beer', label: '啤酒', category: 'other', source: 'lucide' },
  { slug: 'gift', label: '礼物', category: 'other', source: 'lucide' },
  { slug: 'infinity', label: '无限', category: 'other', source: 'lucide' },
  { slug: 'globe', label: '地球', category: 'other', source: 'lucide' },
  { slug: 'snowflake', label: '雪花', category: 'other', source: 'lucide' },
  { slug: 'wind', label: '风', category: 'other', source: 'lucide' },
]

/* ── Migration: FontAwesome -> slug/lucide ─────────── */
const FA_TO_ICON: Record<string, { slug: string; source: 'simple' | 'lucide' }> = {
  'fab fa-github': { slug: 'github', source: 'simple' },
  'fab fa-gitlab': { slug: 'gitlab', source: 'simple' },
  'fab fa-bitbucket': { slug: 'bitbucket', source: 'simple' },
  'fab fa-stack-overflow': { slug: 'stackoverflow', source: 'simple' },
  'fab fa-npm': { slug: 'npm', source: 'simple' },
  'fab fa-docker': { slug: 'docker', source: 'simple' },
  'fab fa-linux': { slug: 'linux', source: 'simple' },
  'fab fa-apple': { slug: 'apple', source: 'simple' },
  'fab fa-windows': { slug: 'windows', source: 'simple' },
  'fab fa-android': { slug: 'android', source: 'simple' },
  'fab fa-aws': { slug: 'aws', source: 'simple' },
  'fab fa-chrome': { slug: 'googlechrome', source: 'simple' },
  'fab fa-firefox': { slug: 'firefox', source: 'simple' },
  'fab fa-edge': { slug: 'microsoftedge', source: 'simple' },
  'fab fa-safari': { slug: 'safari', source: 'simple' },
  'fab fa-python': { slug: 'python', source: 'simple' },
  'fab fa-vuejs': { slug: 'vuedotjs', source: 'simple' },
  'fab fa-react': { slug: 'react', source: 'simple' },
  'fab fa-angular': { slug: 'angular', source: 'simple' },
  'fab fa-node': { slug: 'nodedotjs', source: 'simple' },
  'fab fa-wordpress': { slug: 'wordpress', source: 'simple' },
  'fab fa-youtube': { slug: 'youtube', source: 'simple' },
  'fab fa-bilibili': { slug: 'bilibili', source: 'simple' },
  'fab fa-twitch': { slug: 'twitch', source: 'simple' },
  'fab fa-vimeo': { slug: 'vimeo', source: 'simple' },
  'fab fa-weixin': { slug: 'wechat', source: 'simple' },
  'fab fa-weibo': { slug: 'sinaweibo', source: 'simple' },
  'fab fa-zhihu': { slug: 'zhihu', source: 'simple' },
  'fab fa-qq': { slug: 'tencentqq', source: 'simple' },
  'fab fa-twitter': { slug: 'twitter', source: 'simple' },
  'fab fa-facebook': { slug: 'facebook', source: 'simple' },
  'fab fa-instagram': { slug: 'instagram', source: 'simple' },
  'fab fa-telegram': { slug: 'telegram', source: 'simple' },
  'fab fa-discord': { slug: 'discord', source: 'simple' },
  'fab fa-slack': { slug: 'slack', source: 'simple' },
  'fab fa-reddit': { slug: 'reddit', source: 'simple' },
  'fab fa-linkedin': { slug: 'linkedin', source: 'simple' },
  'fab fa-tiktok': { slug: 'tiktok', source: 'simple' },
  'fab fa-pinterest': { slug: 'pinterest', source: 'simple' },
  'fab fa-amazon': { slug: 'amazon', source: 'simple' },
  'fab fa-paypal': { slug: 'paypal', source: 'simple' },
  'fab fa-stripe': { slug: 'stripe', source: 'simple' },
  'fab fa-alipay': { slug: 'alipay', source: 'simple' },
  'fab fa-btc': { slug: 'bitcoin', source: 'simple' },
  'fab fa-ethereum': { slug: 'ethereum', source: 'simple' },
  'fab fa-cloudflare': { slug: 'cloudflare', source: 'simple' },
  'fab fa-steam': { slug: 'steam', source: 'simple' },
  'fab fa-xbox': { slug: 'xbox', source: 'simple' },
  'fab fa-playstation': { slug: 'playstation', source: 'simple' },
  'fab fa-dropbox': { slug: 'dropbox', source: 'simple' },
  'fab fa-google-drive': { slug: 'googledrive', source: 'simple' },
  'fab fa-onedrive': { slug: 'onedrive', source: 'simple' },
  'fab fa-raspberry-pi': { slug: 'raspberrypi', source: 'simple' },
  'fab fa-digital-ocean': { slug: 'digitalocean', source: 'simple' },
  'fab fa-google-cloud': { slug: 'googlecloud', source: 'simple' },
  'fab fa-microsoft': { slug: 'microsoft', source: 'simple' },
  'fab fa-heroku': { slug: 'heroku', source: 'simple' },
  'fab fa-netlify': { slug: 'netlify', source: 'simple' },
  'fab fa-codepen': { slug: 'codepen', source: 'simple' },
  'fab fa-figma': { slug: 'figma', source: 'simple' },
  'fab fa-markdown': { slug: 'markdown', source: 'simple' },
  'fab fa-jira': { slug: 'jira', source: 'simple' },
  'fab fa-trello': { slug: 'trello', source: 'simple' },
  'fab fa-spotify': { slug: 'spotify', source: 'simple' },
  'fab fa-soundcloud': { slug: 'soundcloud', source: 'simple' },
  'fab fa-imdb': { slug: 'imdb', source: 'simple' },
  'fab fa-snapchat': { slug: 'snapchat', source: 'simple' },
  'fab fa-adobe': { slug: 'adobe', source: 'simple' },
  'fab fa-ebay': { slug: 'ebay', source: 'simple' },
  'fab fa-etsy': { slug: 'etsy', source: 'simple' },
  'fab fa-shopify': { slug: 'shopify', source: 'simple' },
  'fab fa-wix': { slug: 'wix', source: 'simple' },
  'fab fa-squarespace': { slug: 'squarespace', source: 'simple' },
  'fab fa-medium': { slug: 'medium', source: 'simple' },
  'fab fa-product-hunt': { slug: 'producthunt', source: 'simple' },
  'fab fa-hacker-news': { slug: 'hackernews', source: 'simple' },
  'fab fa-kickstarter': { slug: 'kickstarter', source: 'simple' },
  'fab fa-goodreads': { slug: 'goodreads', source: 'simple' },
  'fab fa-magento': { slug: 'magento', source: 'simple' },
  'fab fa-drupal': { slug: 'drupal', source: 'simple' },
  'fab fa-joomla': { slug: 'joomla', source: 'simple' },
  'fab fa-airbnb': { slug: 'airbnb', source: 'simple' },
  'fab fa-uber': { slug: 'uber', source: 'simple' },
  'fab fa-tripadvisor': { slug: 'tripadvisor', source: 'simple' },
  'fab fa-opera': { slug: 'opera', source: 'simple' },
  'fab fa-internet-explorer': { slug: 'internetexplorer', source: 'simple' },
  'fab fa-ubuntu': { slug: 'ubuntu', source: 'simple' },
  'fab fa-centos': { slug: 'centos', source: 'simple' },
  'fab fa-fedora': { slug: 'fedora', source: 'simple' },
  'fab fa-redhat': { slug: 'redhat', source: 'simple' },
  'fab fa-js': { slug: 'javascript', source: 'simple' },
  'fab fa-js-square': { slug: 'javascript', source: 'simple' },
  'fab fa-node-js': { slug: 'nodedotjs', source: 'simple' },
  'fab fa-html5': { slug: 'html5', source: 'simple' },
  'fab fa-css3-alt': { slug: 'css3', source: 'simple' },
  'fab fa-sass': { slug: 'sass', source: 'simple' },
  'fab fa-less': { slug: 'less', source: 'simple' },
  'fab fa-bootstrap': { slug: 'bootstrap', source: 'simple' },
  'fab fa-gulp': { slug: 'gulp', source: 'simple' },
  'fab fa-grunt': { slug: 'grunt', source: 'simple' },
  'fab fa-php': { slug: 'php', source: 'simple' },
  'fab fa-java': { slug: 'java', source: 'simple' },
  'fab fa-swift': { slug: 'swift', source: 'simple' },
  'fab fa-kotlin': { slug: 'kotlin', source: 'simple' },
  'fab fa-flutter': { slug: 'flutter', source: 'simple' },
  'fab fa-vimeo-v': { slug: 'vimeo', source: 'simple' },
  'fab fa-youtube-square': { slug: 'youtube', source: 'simple' },
  'fab fa-steam-square': { slug: 'steam', source: 'simple' },
  'fab fa-facebook-messenger': { slug: 'facebookmessenger', source: 'simple' },
  'fab fa-x-twitter': { slug: 'x', source: 'simple' },
  'fab fa-whatsapp': { slug: 'whatsapp', source: 'simple' },
  'fab fa-skype': { slug: 'skype', source: 'simple' },
  'fab fa-signal': { slug: 'signal', source: 'simple' },
  'fab fa-line': { slug: 'line', source: 'simple' },
  'fab fa-threads': { slug: 'threads', source: 'simple' },
  'fab fa-mastodon': { slug: 'mastodon', source: 'simple' },
  'fab fa-y-combinator': { slug: 'ycombinator', source: 'simple' },
  'fab fa-azure': { slug: 'azure', source: 'simple' },
  'fab fa-google': { slug: 'google', source: 'simple' },
  'fab fa-cuttlefish': { slug: 'cplusplus', source: 'simple' },
  'fab fa-creative-commons': { slug: 'creativecommons', source: 'simple' },
  'fab fa-rust': { slug: 'rust', source: 'simple' },
  'fab fa-go': { slug: 'go', source: 'simple' },
  'fab fa-svelte': { slug: 'svelte', source: 'simple' },
  'fab fa-typescript': { slug: 'typescript', source: 'simple' },
  'fab fa-vercel': { slug: 'vercel', source: 'simple' },
  'fab fa-cc-visa': { slug: 'visa', source: 'simple' },
  'fab fa-cc-mastercard': { slug: 'mastercard', source: 'simple' },
  'fab fa-cc-amex': { slug: 'americanexpress', source: 'simple' },
  'fab fa-cc-paypal': { slug: 'paypal', source: 'simple' },
  'fab fa-kuaishou': { slug: 'kuaishou', source: 'simple' },
  'fab fa-zhihu-square': { slug: 'zhihu', source: 'simple' },
  'fab fa-git': { slug: 'git', source: 'simple' },
  'fab fa-kaggle': { slug: 'kaggle', source: 'simple' },
  'fab fa-deezer': { slug: 'deezer', source: 'simple' },
  'fab fa-lastfm': { slug: 'lastfm', source: 'simple' },
  'fas fa-cloud': { slug: 'cloud', source: 'lucide' },
  'fas fa-download': { slug: 'download', source: 'lucide' },
  'fas fa-upload': { slug: 'upload', source: 'lucide' },
  'fas fa-server': { slug: 'server', source: 'lucide' },
  'fas fa-language': { slug: 'languages', source: 'lucide' },
  'far fa-flag': { slug: 'flag', source: 'lucide' },
  'fas fa-tachometer-alt': { slug: 'gauge', source: 'lucide' },
  'far fa-hdd': { slug: 'hard-drive', source: 'lucide' },
  'fas fa-hdd': { slug: 'hard-drive', source: 'lucide' },
  'fas fa-cog': { slug: 'settings', source: 'lucide' },
  'fas fa-home': { slug: 'home', source: 'lucide' },
  'fas fa-search': { slug: 'search', source: 'lucide' },
  'fas fa-user': { slug: 'user', source: 'lucide' },
  'fas fa-envelope': { slug: 'mail', source: 'lucide' },
  'fas fa-star': { slug: 'star', source: 'lucide' },
  'fas fa-heart': { slug: 'heart', source: 'lucide' },
  'fas fa-bookmark': { slug: 'bookmark', source: 'lucide' },
  'fas fa-bell': { slug: 'bell', source: 'lucide' },
  'fas fa-calendar-alt': { slug: 'calendar', source: 'lucide' },
  'fas fa-clock': { slug: 'clock', source: 'lucide' },
  'fas fa-globe': { slug: 'globe', source: 'lucide' },
  'fas fa-lock': { slug: 'lock', source: 'lucide' },
  'fas fa-unlock': { slug: 'unlock', source: 'lucide' },
  'fas fa-eye': { slug: 'eye', source: 'lucide' },
  'fas fa-film': { slug: 'film', source: 'lucide' },
  'fas fa-video': { slug: 'video', source: 'lucide' },
  'fas fa-music': { slug: 'music', source: 'lucide' },
  'fas fa-headphones': { slug: 'headphones', source: 'lucide' },
  'fas fa-camera': { slug: 'camera', source: 'lucide' },
  'fas fa-images': { slug: 'image', source: 'lucide' },
  'fas fa-palette': { slug: 'palette', source: 'lucide' },
  'fas fa-code': { slug: 'code', source: 'lucide' },
  'fas fa-terminal': { slug: 'terminal', source: 'lucide' },
  'fas fa-database': { slug: 'database', source: 'lucide' },
  'fas fa-chart-bar': { slug: 'bar-chart-3', source: 'lucide' },
  'fas fa-chart-line': { slug: 'trending-up', source: 'lucide' },
  'fas fa-print': { slug: 'printer', source: 'lucide' },
  'fas fa-folder': { slug: 'folder', source: 'lucide' },
  'fas fa-folder-open': { slug: 'folder-open', source: 'lucide' },
  'fas fa-file': { slug: 'file', source: 'lucide' },
  'fas fa-file-alt': { slug: 'file-text', source: 'lucide' },
  'fas fa-file-pdf': { slug: 'file-text', source: 'lucide' },
  'fas fa-file-word': { slug: 'file-text', source: 'lucide' },
  'fas fa-file-excel': { slug: 'file-spreadsheet', source: 'lucide' },
  'fas fa-file-image': { slug: 'file-image', source: 'lucide' },
  'fas fa-file-archive': { slug: 'file-archive', source: 'lucide' },
  'fas fa-file-code': { slug: 'file-code', source: 'lucide' },
  'fas fa-gamepad': { slug: 'gamepad-2', source: 'lucide' },
  'fas fa-keyboard': { slug: 'keyboard', source: 'lucide' },
  'fas fa-mouse': { slug: 'mouse', source: 'lucide' },
  'fas fa-wifi': { slug: 'wifi', source: 'lucide' },
  'fas fa-sync': { slug: 'refresh-cw', source: 'lucide' },
  'fas fa-sync-alt': { slug: 'refresh-cw', source: 'lucide' },
  'fas fa-history': { slug: 'history', source: 'lucide' },
  'fas fa-qrcode': { slug: 'qrcode', source: 'lucide' },
  'fas fa-link': { slug: 'link', source: 'lucide' },
  'fas fa-external-link-alt': { slug: 'external-link', source: 'lucide' },
  'fas fa-arrow-right': { slug: 'arrow-right', source: 'lucide' },
  'fas fa-arrow-left': { slug: 'arrow-left', source: 'lucide' },
  'fas fa-arrow-up': { slug: 'arrow-up', source: 'lucide' },
  'fas fa-arrow-down': { slug: 'arrow-down', source: 'lucide' },
  'fas fa-wrench': { slug: 'wrench', source: 'lucide' },
  'fas fa-tools': { slug: 'wrench', source: 'lucide' },
  'fas fa-calculator': { slug: 'calculator', source: 'lucide' },
  'fas fa-clipboard-list': { slug: 'list-checks', source: 'lucide' },
  'fas fa-microphone': { slug: 'mic', source: 'lucide' },
  'fas fa-podcast': { slug: 'mic', source: 'lucide' },
  'fas fa-photo-video': { slug: 'image', source: 'lucide' },
  'fas fa-camera-retro': { slug: 'camera', source: 'lucide' },
  'fas fa-comments': { slug: 'message-square', source: 'lucide' },
  'fas fa-share-alt': { slug: 'share-2', source: 'lucide' },
  'fas fa-rss': { slug: 'rss', source: 'lucide' },
  'fas fa-desktop': { slug: 'monitor', source: 'lucide' },
  'fas fa-laptop': { slug: 'laptop', source: 'lucide' },
  'fas fa-tablet-alt': { slug: 'tablet', source: 'lucide' },
  'fas fa-mobile-alt': { slug: 'smartphone', source: 'lucide' },
  'fas fa-microchip': { slug: 'cpu', source: 'lucide' },
  'fas fa-memory': { slug: 'cpu', source: 'lucide' },
  'fas fa-bolt': { slug: 'zap', source: 'lucide' },
  'fas fa-lightbulb': { slug: 'lightbulb', source: 'lucide' },
  'fas fa-moon': { slug: 'moon', source: 'lucide' },
  'fas fa-sun': { slug: 'sun', source: 'lucide' },
  'fas fa-book': { slug: 'book', source: 'lucide' },
  'fas fa-newspaper': { slug: 'newspaper', source: 'lucide' },
  'fas fa-graduation-cap': { slug: 'graduation-cap', source: 'lucide' },
  'fas fa-tag': { slug: 'tag', source: 'lucide' },
  'fas fa-flag': { slug: 'flag', source: 'lucide' },
  'fas fa-crown': { slug: 'crown', source: 'lucide' },
  'fas fa-gem': { slug: 'gem', source: 'lucide' },
  'fas fa-fire': { slug: 'flame', source: 'lucide' },
  'fas fa-medal': { slug: 'medal', source: 'lucide' },
  'fas fa-trophy': { slug: 'trophy', source: 'lucide' },
  'fas fa-blog': { slug: 'pen-tool', source: 'lucide' },
  'fas fa-magic': { slug: 'wand-2', source: 'lucide' },
  'fas fa-cart-plus': { slug: 'shopping-cart', source: 'lucide' },
  'fas fa-shopping-cart': { slug: 'shopping-cart', source: 'lucide' },
  'fas fa-map-marker-alt': { slug: 'map-pin', source: 'lucide' },
  'fas fa-network-wired': { slug: 'globe', source: 'lucide' },
  'fas fa-shield-alt': { slug: 'shield', source: 'lucide' },
  'fas fa-user-friends': { slug: 'users', source: 'lucide' },
  'fas fa-sign-in-alt': { slug: 'log-in', source: 'lucide' },
  'fas fa-sign-out-alt': { slug: 'log-out', source: 'lucide' },
  'fas fa-undo': { slug: 'undo', source: 'lucide' },
  'fas fa-redo': { slug: 'redo', source: 'lucide' },
  'fas fa-chevron-right': { slug: 'chevron-right', source: 'lucide' },
  'fas fa-chevron-left': { slug: 'chevron-left', source: 'lucide' },
  'fas fa-chevron-up': { slug: 'chevron-up', source: 'lucide' },
  'fas fa-chevron-down': { slug: 'chevron-down', source: 'lucide' },
  'fas fa-angle-double-right': { slug: 'chevrons-right', source: 'lucide' },
  'fas fa-angle-double-left': { slug: 'chevrons-left', source: 'lucide' },
  'fas fa-folder-plus': { slug: 'folder-plus', source: 'lucide' },
  'fas fa-folder-minus': { slug: 'folder-minus', source: 'lucide' },
  'fas fa-copy': { slug: 'copy', source: 'lucide' },
  'fas fa-paste': { slug: 'clipboard-paste', source: 'lucide' },
  'fas fa-cut': { slug: 'scissors', source: 'lucide' },
  'fas fa-save': { slug: 'save', source: 'lucide' },
  'fas fa-archive': { slug: 'archive', source: 'lucide' },
  'fas fa-play-circle': { slug: 'play-circle', source: 'lucide' },
  'fas fa-cloud-upload-alt': { slug: 'upload', source: 'lucide' },
  'fas fa-cloud-download-alt': { slug: 'download', source: 'lucide' },
  'fas fa-sd-card': { slug: 'sd-card', source: 'lucide' },
  'fas fa-sim-card': { slug: 'sim-card', source: 'lucide' },
  'fas fa-plug': { slug: 'plug', source: 'lucide' },
  'fas fa-battery-full': { slug: 'battery-full', source: 'lucide' },
  'fas fa-battery-half': { slug: 'battery-medium', source: 'lucide' },
  'fas fa-battery-empty': { slug: 'battery-low', source: 'lucide' },
  'fas fa-fax': { slug: 'printer', source: 'lucide' },
  'fas fa-file-powerpoint': { slug: 'presentation', source: 'lucide' },
  'fas fa-file-audio': { slug: 'file-audio', source: 'lucide' },
  'fas fa-file-video': { slug: 'file-video', source: 'lucide' },
  'fas fa-file-csv': { slug: 'file-spreadsheet', source: 'lucide' },
  'fas fa-dollar-sign': { slug: 'dollar-sign', source: 'lucide' },
  'fas fa-euro-sign': { slug: 'euro', source: 'lucide' },
  'fas fa-yen-sign': { slug: 'yen', source: 'lucide' },
  'fas fa-coins': { slug: 'coins', source: 'lucide' },
  'fas fa-money-bill': { slug: 'banknote', source: 'lucide' },
  'fas fa-money-bill-wave': { slug: 'banknote', source: 'lucide' },
  'fas fa-credit-card': { slug: 'credit-card', source: 'lucide' },
  'fas fa-wallet': { slug: 'wallet', source: 'lucide' },
  'fas fa-piggy-bank': { slug: 'piggy-bank', source: 'lucide' },
  'fas fa-chart-pie': { slug: 'pie-chart', source: 'lucide' },
  'fas fa-percentage': { slug: 'percent', source: 'lucide' },
  'fas fa-bank': { slug: 'landmark', source: 'lucide' },
  'fas fa-hand-holding-usd': { slug: 'wallet', source: 'lucide' },
  'fas fa-key': { slug: 'key', source: 'lucide' },
  'fas fa-shield': { slug: 'shield', source: 'lucide' },
  'fas fa-broadcast-tower': { slug: 'radio', source: 'lucide' },
  'fas fa-tv': { slug: 'tv', source: 'lucide' },
  'fas fa-paperclip': { slug: 'paperclip', source: 'lucide' },
  'fas fa-scissors': { slug: 'scissors', source: 'lucide' },
  'fas fa-compass': { slug: 'compass', source: 'lucide' },
  'fas fa-map': { slug: 'map', source: 'lucide' },
}

export function migrateIcon(icon: string): { slug: string; source: 'simple' | 'lucide' } | null {
  if (!icon) return null
  const mapped = FA_TO_ICON[icon]
  if (mapped) return mapped
  return null
}

/* ── Smart icon: domain → simple slug ─────────────── */
const DOMAIN_MAP: Record<string, string> = {
  // Development / Code hosting
  'github.com': 'github', 'gitlab.com': 'gitlab', 'bitbucket.org': 'bitbucket',
  'stackoverflow.com': 'stackoverflow', 'stackexchange.com': 'stackexchange',
  'codepen.io': 'codepen', 'codesandbox.io': 'codesandbox',
  'replit.com': 'replit', 'gitpod.io': 'gitpod', 'sourceforge.net': 'sourceforge',
  'gitee.com': 'gitee', 'coding.net': 'coding',
  'npmjs.com': 'npm', 'pypi.org': 'pypi', 'crates.io': 'rust',
  'maven.apache.org': 'apachemaven', 'gradle.org': 'gradle',
  'nuget.org': 'nuget', 'hub.docker.com': 'docker',

  // CI / DevOps
  'jenkins.io': 'jenkins', 'travis-ci.com': 'travisci',
  'circleci.com': 'circleci', 'githubactions.com': 'githubactions',
  'codecov.io': 'codecov', 'sonarcloud.io': 'sonarcloud',

  // Programming languages & tools
  'python.org': 'python', 'nodejs.org': 'nodedotjs', 'deno.land': 'deno',
  'rust-lang.org': 'rust', 'golang.org': 'go', 'kotlinlang.org': 'kotlin',
  'swift.org': 'swift', 'php.net': 'php', 'java.com': 'java',
  'typescriptlang.org': 'typescript', 'flutter.dev': 'flutter',
  'dart.dev': 'dart', 'elixir-lang.org': 'elixir',
  'ruby-lang.org': 'ruby', 'perl.org': 'perl', 'haskell.org': 'haskell',
  'scala-lang.org': 'scala', 'racket-lang.org': 'racket',
  'ocaml.org': 'ocaml', 'julialang.org': 'julia',
  'clojure.org': 'clojure', 'lua.org': 'lua', 'crystal-lang.org': 'crystal',

  // Frameworks
  'react.dev': 'react', 'vuejs.org': 'vuedotjs', 'angular.io': 'angular',
  'svelte.dev': 'svelte', 'nextjs.org': 'nextdotjs', 'nuxt.com': 'nuxtdotjs',
  'nestjs.com': 'nestjs', 'expressjs.com': 'express', 'graphql.org': 'graphql',
  'djangoproject.com': 'django', 'rubyonrails.org': 'rubyonrails',
  'laravel.com': 'laravel', 'spring.io': 'spring', 'symfony.com': 'symfony',
  'electronjs.org': 'electron', 'tauri.app': 'tauri', 'gatsbyjs.com': 'gatsby',
  'jekyllrb.com': 'jekyll', 'hugothemes.com': 'hugo',

  // Design
  'figma.com': 'figma', 'zeplin.io': 'zeplin', 'sketch.com': 'sketch',
  'adobe.com': 'adobe', 'canva.com': 'canva', 'dribbble.com': 'dribbble',
  'behance.net': 'behance', 'unsplash.com': 'unsplash',

  // Browsers
  'google.com/chrome': 'googlechrome', 'mozilla.org': 'firefox',
  'opera.com': 'opera', 'apple.com/safari': 'safari',
  'microsoft.com/edge': 'microsoftedge', 'brave.com': 'brave',
  'torproject.org': 'tor', 'vivaldi.com': 'vivaldi',

  // Cloud & Hosting
  'aws.amazon.com': 'amazonwebservices', 'cloud.aws': 'amazonwebservices',
  'aws.com': 'amazonwebservices', 'console.aws.amazon.com': 'amazonwebservices',
  'cloud.google.com': 'googlecloud', 'azure.microsoft.com': 'azure',
  'digitalocean.com': 'digitalocean', 'linode.com': 'linode',
  'vultr.com': 'vultr', 'heroku.com': 'heroku', 'netlify.app': 'netlify',
  'vercel.app': 'vercel', 'vercel.com': 'vercel', 'cloudflare.com': 'cloudflare',
  'cloudfront.net': 'amazoncloudfront',
  'firebase.google.com': 'firebase', 'supabase.com': 'supabase',
  'fly.io': 'flydotio', 'railway.app': 'railway', 'render.com': 'render',
  'backblaze.com': 'backblaze', 'wasabi.com': 'wasabi',

  // Databases
  'mysql.com': 'mysql', 'postgresql.org': 'postgresql',
  'mongodb.com': 'mongodb', 'redis.io': 'redis', 'sqlite.org': 'sqlite',
  'cassandra.apache.org': 'apachecassandra', 'couchdb.apache.org': 'couchdb',
  'neo4j.com': 'neo4j', 'elastic.co': 'elasticsearch',

  // AI & ML
  'openai.com': 'openai', 'huggingface.co': 'huggingface',
  'tensorflow.org': 'tensorflow', 'pytorch.org': 'pytorch',
  'keras.io': 'keras', 'jupyter.org': 'jupyter',
  'anaconda.com': 'anaconda', 'deepmind.com': 'deepmind',
  'anthropic.com': 'anthropic', 'perplexity.ai': 'perplexity',

  // Social
  'twitter.com': 'twitter', 'x.com': 'x', 'facebook.com': 'facebook',
  'instagram.com': 'instagram', 'linkedin.com': 'linkedin',
  'tiktok.com': 'tiktok', 'snapchat.com': 'snapchat', 'pinterest.com': 'pinterest',
  'reddit.com': 'reddit', 'tumblr.com': 'tumblr', 'flickr.com': 'flickr',
  'threads.net': 'threads', 'mastodon.social': 'mastodon',
  'bluesky.com': 'bluesky',
  'weibo.com': 'sinaweibo', 'zhihu.com': 'zhihu',
  'douban.com': 'douban', 'xiaohongshu.com': 'xiaohongshu',
  'bilibili.com': 'bilibili', 'douyin.com': 'tiktok',

  // Media
  'youtube.com': 'youtube', 'twitch.tv': 'twitch', 'vimeo.com': 'vimeo',
  'dailymotion.com': 'dailymotion', 'spotify.com': 'spotify',
  'soundcloud.com': 'soundcloud', 'deezer.com': 'deezer',
  'last.fm': 'lastfm', 'bandcamp.com': 'bandcamp',

  // Messaging
  'telegram.org': 'telegram', 'discord.com': 'discord',
  'slack.com': 'slack', 'skype.com': 'skype',
  'whatsapp.com': 'whatsapp', 'line.me': 'line',
  'messenger.com': 'facebookmessenger', 'zoom.us': 'zoom',
  'teams.microsoft.com': 'microsoftteams', 'meet.google.com': 'googlemeet',
  'wechat.com': 'wechat', 'signal.org': 'signal',
  'element.io': 'element', 'rocket.chat': 'rocketdotchat',

  // Email
  'mail.google.com': 'gmail', 'outlook.com': 'outlook',
  'proton.me': 'protonmail', 'protonmail.com': 'protonmail',
  'mail.ru': 'maildotru',
  'fastmail.com': 'fastmail', 'yandex.com': 'yandex',

  // Productivity & Office
  'docs.google.com': 'googledocs', 'sheets.google.com': 'googlesheets',
  'slides.google.com': 'googleslides', 'drive.google.com': 'googledrive',
  'calendar.google.com': 'googlecalendar', 'keep.google.com': 'googlekeep',
  'office.com': 'microsoftoffice', 'office365.com': 'microsoftoffice',
  'notion.com': 'notion', 'notion.so': 'notion',
  'evernote.com': 'evernote', 'obsidian.md': 'obsidian',
  'trello.com': 'trello', 'monday.com': 'monday',
  'asana.com': 'asana', 'clickup.com': 'clickup',
  'airtable.com': 'airtable', 'miro.com': 'miro',
   'confluence.com': 'confluence',

  // Cloud storage
  'dropbox.com': 'dropbox', 'onedrive.com': 'onedrive',
  'box.com': 'box', 'mega.io': 'mega', 'pcloud.com': 'pcloud',
  'icloud.com': 'icloud', 'nextcloud.com': 'nextcloud',

  // Payment & Finance
  'paypal.com': 'paypal', 'stripe.com': 'stripe', 'alipay.com': 'alipay',
  'wechatpay.com': 'wechatpay', 'square.com': 'square',
  'wise.com': 'wise', 'revolut.com': 'revolut',
  'coinbase.com': 'coinbase', 'binance.com': 'binance',
  'robinhood.com': 'robinhood',

  // E-commerce
  'amazon.com': 'amazon', 'amazon.cn': 'amazon', 'amazon.co.jp': 'amazon',
  'ebay.com': 'ebay', 'etsy.com': 'etsy', 'shopify.com': 'shopify',
  'taobao.com': 'taobao', 'tmall.com': 'tmall',
  'jd.com': 'jd', 'pinduoduo.com': 'pinduoduo',
  'aliexpress.com': 'aliexpress', 'bestbuy.com': 'bestbuy',
  'walmart.com': 'walmart', 'target.com': 'target',
  'ikea.com': 'ikea', 'costco.com': 'costco',

  // Travel
  'airbnb.com': 'airbnb', 'uber.com': 'uber', 'tripadvisor.com': 'tripadvisor',
  'booking.com': 'bookingdotcom', 'expedia.com': 'expedia',
  'lyft.com': 'lyft', 'didiglobal.com': 'didi',
  'ctrip.com': 'ctrip', 'fliggy.com': 'fliggy',
  'meituan.com': 'meituan', 'dianping.com': 'dianping',

  // Gaming
  'steampowered.com': 'steam', 'xbox.com': 'xbox', 'playstation.com': 'playstation',
  'nintendo.com': 'nintendo', 'epicgames.com': 'epicgames',
  'roblox.com': 'roblox', 'minecraft.net': 'minecraft',
  'rockstargames.com': 'rockstargames', 'ea.com': 'ea',
  'ubisoft.com': 'ubisoft', 'blizzard.com': 'blizzard',
  'leagueoflegends.com': 'leagueoflegends', 'valorant.com': 'valorant',
  'fortnite.com': 'fortnite', 'genshin.hoyoverse.com': 'genshinimpact',

  // Streaming
'imdb.com': 'imdb',
  'crunchyroll.com': 'crunchyroll', 'funimation.com': 'funimation',
  'pornhub.com': 'pornhub',

  // News & Content
  'medium.com': 'medium', 'substack.com': 'substack',
  'news.ycombinator.com': 'hackernews',
  'theverge.com': 'theverge', 'techcrunch.com': 'techcrunch',
  'arstechnica.com': 'arstechnica', 'wired.com': 'wired',
  'bbc.com': 'bbc', 'cnn.com': 'cnn', 'nytimes.com': 'nytimes',
  'bloomberg.com': 'bloomberg', 'reuters.com': 'reuters',
  '36kr.com': '36kr', 'huxiu.com': 'huxiu',
  'sspai.com': 'sspai', 'ifanr.com': 'ifanr',

  // Technology
  'kernel.org': 'linux', 'linux.org': 'linux',
  'ubuntu.com': 'ubuntu', 'debian.org': 'debian',
  'centos.org': 'centos', 'redhat.com': 'redhat',
  'fedora.org': 'fedora', 'archlinux.org': 'archlinux',
  'alpinelinux.org': 'alpinelinux', 'manjaro.org': 'manjaro',
  'apple.com': 'apple', 'microsoft.com': 'microsoft',
  'google.com': 'google', 'ibm.com': 'ibm', 'oracle.com': 'oracle',

  // Education
  'wikipedia.org': 'wikipedia', 'wikimedia.org': 'wikimedia',
  'coursera.org': 'coursera', 'udemy.com': 'udemy',
  'edx.org': 'edx', 'khanacademy.org': 'khanacademy',
  'duolingo.com': 'duolingo', 'codecademy.com': 'codecademy',

  // Maps & Navigation
  'maps.google.com': 'googlemaps', 'openstreetmap.org': 'openstreetmap',
  'amap.com': 'amap', 'gaode.com': 'amap',
  'baidu.com/map': 'baidu',

  // Other
  'wordpress.com': 'wordpress', 'wix.com': 'wix',
  'squarespace.com': 'squarespace', 'godaddy.com': 'godaddy',
  'namecheap.com': 'namecheap', 'cloudns.net': 'cloudns',
  'logitech.com': 'logitech', 'samsung.com': 'samsung',
  'xiaomi.com': 'xiaomi', 'huawei.com': 'huawei',
  'docker.com': 'docker', 'docker.io': 'docker',
  'kubernetes.io': 'kubernetes', 'terraform.io': 'terraform',
  'ansible.com': 'ansible', 'puppet.com': 'puppet',
  'chef.io': 'chef', 'grafana.com': 'grafana',
  'prometheus.io': 'prometheus', 'datadoghq.com': 'datadog',
  'newrelic.com': 'newrelic', 'sentry.io': 'sentry',
  'gitkraken.com': 'gitkraken', 'sourcegraph.com': 'sourcegraph',
  'jira.com': 'jira',
  'raspberrypi.com': 'raspberrypi', 'arduino.cc': 'arduino',
  'espressif.com': 'espressif', 'nvidia.com': 'nvidia',
  'intel.com': 'intel', 'amd.com': 'amd',
  'genymotion.com': 'genymotion', 'android.com': 'android',
  'qemu.org': 'qemu', 'vmware.com': 'vmware',
  'virtualbox.org': 'virtualbox', 'tailscale.com': 'tailscale',
   'ngrok.com': 'ngrok',
  'postman.com': 'postman', 'insomnia.rest': 'insomnia',
  'swagger.io': 'swagger', 'hasura.io': 'hasura',

  // Chinese services
  'baidu.com': 'baidu', 'qiyi.com': 'iqiyi', 'youku.com': 'youku',
  'tencent.com': 'tencentqq', 'qq.com': 'tencentqq',
  '163.com': 'netease', '126.com': 'netease',
  'sina.com.cn': 'sina', 'sohu.com': 'sohu',
  'csdn.net': 'csdn', 'jianshu.com': 'jianshu',
  'segmentfault.com': 'segmentfault',
  'chunyu.com': 'chunyu',
  'lvmama.com': 'lvmama', 'qunar.com': 'qunar',
  'fang.com': 'anjuke', 'anjuke.com': 'anjuke',
  'zhongan.com': 'zhongan',
}

/* ── Content keyword matching ──────────────────────── */
const TITLE_KEYWORDS: [RegExp, string][] = [
  [/github/i, 'github'], [/gitlab/i, 'gitlab'],
  [/youtube/i, 'youtube'], [/哔哩哔哩|bilibili|b站/i, 'bilibili'],
  [/twitter|推特/i, 'twitter'], [/weibo|微博/i, 'sinaweibo'],
  [/zhihu|知乎/i, 'zhihu'], [/wechat|微信/i, 'wechat'],
  [/qq\b|腾讯/i, 'tencentqq'], [/douyin|抖音/i, 'tiktok'],
  [/douban|豆瓣/i, 'douban'], [/instagram/i, 'instagram'],
  [/facebook/i, 'facebook'], [/linkedin|领英/i, 'linkedin'],
  [/spotify/i, 'spotify'], [/netflix/i, 'netflix'],
  [/amazon/i, 'amazon'], [/百度|baidu/i, 'baidu'],
  [/google/i, 'google'], [/microsoft/i, 'microsoft'],
  [/apple/i, 'apple'], [/notion/i, 'notion'],
  [/docker/i, 'docker'], [/kubernetes|k8s/i, 'kubernetes'],
  [/chatgpt|openai|chat ?gpt/i, 'openai'],
  [/claude|anthropic/i, 'anthropic'],
  [/copilot|github ?copilot/i, 'github'],
]

export function smartIcon(url: string, title?: string): { slug: string; source: 'simple' | 'lucide' } {
  // Try title keyword matching first (strongest signal)
  if (title) {
    for (const [pattern, slug] of TITLE_KEYWORDS) {
      if (pattern.test(title)) {
        return { slug, source: 'simple' }
      }
    }
  }

  if (!url) return { slug: 'link', source: 'lucide' }
  try {
    const u = new URL(url)
    let host = u.hostname.replace(/^www\./, '')
    const path = u.pathname

    // full hostname match
    if (DOMAIN_MAP[host]) return { slug: DOMAIN_MAP[host], source: 'simple' }

    // hostname + path prefix match (e.g. "google.com/maps")
    for (const [key, slug] of Object.entries(DOMAIN_MAP)) {
      if (path && host + path.startsWith(key)) {
        return { slug, source: 'simple' }
      }
    }

    // parent domain
    const parts = host.split('.')
    if (parts.length >= 2) {
      const parent = parts.slice(-2).join('.')
      if (DOMAIN_MAP[parent]) return { slug: DOMAIN_MAP[parent], source: 'simple' }
    }

    // try root domain as simple icon slug
    const root = parts.length >= 2 ? parts.slice(-2).join('.') : host
    const clean = root.replace(/\.(com|cn|org|net|io|app|dev|me|gov|edu|co|uk|jp|de|fr|ru|br|au)$/, '')
    if (clean && clean.length > 1 && clean.length < 40) {
      return { slug: clean, source: 'simple' }
    }
  } catch {}
  return { slug: 'link', source: 'lucide' }
}
